name: "Collaboration Cycle Kickoff"
description: "Kick off the Collaboration Cycle process for your product"
title: "Collaboration Cycle for [Team Name, Product Name, Feature Name]"
labels: ["collab-cycle-review", "collaboration-cycle", "CC-Request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "# Get started with the Collaboration Cycle"
  - type: markdown
    attributes:
      value: |
        This ticket initiates the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) for your team's product or feature. The Collaboration Cycle helps teams who are building products on VA.gov and/or the VA Mobile App get feedback and guidance on their product/feature throughout their project's lifecycle to ensure their work meets VA.gov experience standards. Learn more about the [Collaboration Cycle kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff).
  - type: markdown
    attributes:
      value: "## Team and product information"
  - type: input
    id: product-team
    attributes:
      label: Your team name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: product-name
    attributes:
      label: Product name
      description: See [terms and definitions on products vs. features](https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition).
    validations:
      required: true
  - type: input
    id: feature-name
    attributes:
      label: Feature name
      description: See [terms and definitions on products vs. features](https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition).
    validations:
      required: true
  - type: input
    id: team-label
    attributes:
      label: GitHub label for team
      description: Enter a label from the va.gov-team repo. Your team label must be different than your product label.
    validations:
      required: true
  - type: input
    id: product-label
    attributes:
      label: GitHub label for product
      description: Enter a label from the va.gov-team repo. Your product label must be different than your team label.
    validations:
      required: true
  - type: input
    id: feature-label
    attributes:
      label: GitHub label for feature
      description: Enter a label from the va.gov-team repo, if applicable.
    validations:
      required: false
  - type: input
    id: slack-channel
    attributes:
      label: Public DSVA Slack channel for VFS team
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Kickoff questions"
  - type: markdown
    attributes:
      value: |
        Please refer to the guidance on the [Collaboration Cycle Kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff) page on Platform Website for detailed information and examples regarding these questions.
  - type: dropdown
    id: intended-audience
    attributes:
      label: Who is the primary audience for this product?
      options:
        - "Individuals (Veterans, their caregivers, families, survivors, or representatives directly supporting a Veteran)"
        - "Organizations (e.g., VA employees, contractors, representatives working in an organizational capacity, etc.)"
  - type: dropdown
    id: visible-changes
    attributes:
      label: Will your work result in visible changes to the user experience?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: mobile-web
    attributes:
      label: Where will your product live?
      description: If you are building a product for VA.gov and the VA Mobile App then you must bring the product through the Collaboration Cycle twice, once for each domain.
      options:
        - "VA.gov"
        - "VA Mobile App"
    validations:
      required: true
  - type: dropdown
    id: octo-ves
    attributes:
      label: Is your team an OCTO or VES team?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: input
    id: form
    attributes:
      label: If your work involves changes to VA forms, enter the form numbers.
      description: Example 10-10EZ-S and 21-526EZ
      placeholder: 
  - type: input
    id: form-link
    attributes:
      label: If your work involves changes to VA forms, enter the links to the PDFs from Find a Form on VA.gov.
      description: Use [VA Find a Form](https://www.va.gov/find-forms/). Example https://www.va.gov/vaforms/medical/pdf/VA%20Form%2010-10EZ.pdf and https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf.
      placeholder:
  - type: markdown
    attributes:
      value: "## Artifacts"
  - type: input
    id: team-manifest
    attributes:
      label: Team manifest
      description: Please enter a URL for your team manifest, located in the the [`teams` folder of the `va.gov-team-sensitive` repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams). If you don't have one yet, please add one before completing this ticket.
    validations:
      required: true
  - type: input
    id: product-outline
    attributes:
      label: Product outline
      description: Please enter a URL for your product in the Product Directory. If your product isn't in the directory, or needs to be updated, [Request an update to the Product directory](https://github.com/department-of-veterans-affairs/product-directory/issues/new?template=update-product-request.yml).
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Next steps"
